url: "https://blasteoroid-corporation-kbps10240.github.io/Pass-Vault/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
timezone: UTC

defaults:
  -
    scope:
      path: ""
      type: page
    values:
      layout: some_default
  -
    scope:
      path: "static_files/excluded.pdf"
    values:
      sitemap: true
  -
    scope:
      path: "static_files/html_file.html"
    values:
      sitemap: true
